export const BibleOrder = [
  'בראשית',
  'שמות',
  'ויקרא',
  'במדבר',
  'דברים',
  'יהושע',
  'שופטים',
  'שמואל א',
  'שמואל ב',
  'מלכים א',
  'מלכים ב',
  'ישעיהו',
  'ירמיהו',
  'יחזקאל',
  'הושע',
  'יואל',
  'עמוס',
  'עובדיה',
  'יונה',
  'מיכה',
  'נחום',
  'חבקוק',
  'צפניה',
  'חגי',
  'זכריה',
  'מלאכי',
  'תהילים',
  'משלי',
  'איוב',
  'שיר השירים',
  'רות',
  'איכה',
  'קהלת',
  'אסתר',
  'דניאל',
  'עזרא',
  'נחמיה',
  'דברי הימים א',
  'דברי הימים ב',
];

export enum BibleBooks {
  בראשית = 'Genesis',
  שמות = 'Exodus',
  ויקרא = 'Leviticus',
  במדבר = 'Numbers',
  דברים = 'Deuteronomy',
  יהושע = 'Joshua',
  שופטים = 'Judges',
  שמואל_א = '1 Samuel',
  שמואל_ב = '2 Samuel',
  מלכים_א = '1 Kings',
  מלכים_ב = '2 Kings',
  ישעיהו = 'Isaiah',
  ירמיהו = 'Jeremiah',
  יחזקאל = 'Ezekiel',
  הושע = 'Hosea',
  יואל = 'Joel',
  עמוס = 'Amos',
  עובדיה = 'Obadiah',
  יונה = 'Jonah',
  מיכה = 'Micah',
  נחום = 'Nahum',
  חבקוק = 'Habakkuk',
  צפניה = 'Zephaniah',
  חגי = 'Haggai',
  זכריה = 'Zechariah',
  מלאכי = 'Malachi',
  תהילים = 'Psalms',
  משלי = 'Proverbs',
  איוב = 'Job',
  שיר_השירים = 'Song of Solomon',
  רות = 'Ruth',
  איכה = 'Lamentations',
  קהלת = 'Ecclesiastes',
  אסתר = 'Esther',
  דניאל = 'Daniel',
  עזרא = 'Ezra',
  נחמיה = 'Nehemiah',
  דברי_הימים_א = '1 Chronicles',
  דברי_הימים_ב = '2 Chronicles',
}
