name: Deploy Client to EC2 from GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/bibleKey.pem
          chmod 600 ~/.ssh/bibleKey.pem
          ssh-keyscan -H ec2-13-50-54-221.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Install dependencies and build client
        run: |
          cd client
          npm set legacy-peer-deps true
          rm -rf node_modules
          npm cache clean --force
          npm install
          npm run build:prod

      - name: Copy build folder to EC2
        run: |
          scp -i ~/.ssh/bibleKey.pem -r client/build ubuntu@ec2-13-50-54-221.eu-north-1.compute.amazonaws.com:/home/ubuntu/Daily-Bible/client

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/bibleKey.pem ubuntu@ec2-13-50-54-221.eu-north-1.compute.amazonaws.com << 'EOF'
            cd Daily-Bible
            git reset --hard origin/main
            cd client
            npm install
            pm2 startOrRestart ecosystem.config.cjs --only client || pm2 start ecosystem.config.cjs --only client
          EOF
